AtYourService/atyourservice/site/routes.py
from flask import Blueprint, render_template, jsonify, redirect, url_for, flash, request, make_response
from atyourservice import db, bcrypt
from atyourservice.forms.forms import AddMoneyForm, LoginForm, PostJobForm, RegistrationForm
from models import User, JobPost, Transaction, RemovedPost
from flask_login import current_user, login_user, logout_user, login_required
from datetime import datetime
import requests

site = Blueprint('site', __name__)


@site.route('/', methods=["GET", "POST"])
def index():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            flash("there is already a user with this email.", "warning")
            return render_template('index.html', title="At Your Service!", form=form)
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash("Account Created!", 'success')
        return redirect(url_for('site.home'))
    return render_template('index.html', title="At Your Service!", form=form)


@site.route("/logout/")
def logout():
    logout_user()
    flash("you've been logged out!", "warning")
    return redirect(url_for('site.index'))

@site.route("/aboutUs/")
def aboutUs():
    return render_template('aboutUs.html', title="At Your Service!")


@site.route('/login/', methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('site.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('site.home'))
        else:
            flash('Login Unsuccessful. Please check email and password.', 'warning')
    else:
        print("not validated")
    return render_template('login.html', title="At Your Service!", form_name="Login", form=form)


@site.route('/register/', methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('site.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            flash("there is already a user with this email.", "warning")
            return render_template('index.html', title="At Your Service!", form=form)
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash("Account Created!", 'success')
        return redirect(url_for('site.home'))
    return render_template('register.html', title="At Your Service!", form=form, form_name="Register")


@site.route('/home/', methods=["GET", "POST"])
@login_required
def home():
    form = PostJobForm()
    if form.validate_on_submit():
        if float(form.price.data) < 0:
            flash("Please make sure your price is a positive value.", "danger")
            return redirect(url_for('site.home'))
        else:
            post = JobPost(title=form.title.data, job_description=form.description.data,
                           area_name=form.location.data, price=form.price.data, user_id=current_user.id, time=form.time.data)
            db.session.add(post)
            db.session.commit()
            flash(
                "Job posted! an admin will verify your post and it will be made public.", "success")
            return redirect(url_for('site.home'))
    return render_template('home.html', title="At Your Service!", form=form)

# DO NOT change these urls; finicky integration with javascript post paging.
# If you change these, make sure you know what you're doing!
@site.route('/take_job/')
def takeJob_():
    return redirect(url_for('site.home'))


@site.route('/take_job/<int:job_num>/')
def takeJob(job_num):
    if not current_user.is_authenticated:
        flash("You cannot take jobs unless you are logged in.", "error")
        return redirect(url_for("site.index"))
    post = JobPost.query.filter_by(id=job_num).first()
    if post.taken_by:
        flash("sorry! This job was taken while you were browsing.", "error")
        return redirect((url_for("site.home")))
    post.taken_by = current_user.id
    db.session.commit()
    flash("Job taken! Their contact info can be found below by clicking on that job.", "success")
    return(redirect(url_for('site.inspectUser')))
    return job_num
# end cautiousness.


@site.route('/user/')
@login_required
def inspectUser():
    # show jobs taken
    taken = JobPost.query.filter_by(taken_by=current_user.id).all()
    posted = JobPost.query.filter_by(user_id=current_user.id).all()
    return render_template('inspectUser.html', title='At Your Service!', taken=taken, posted=posted)


@site.route('/about/')
def about():
    return render_template('inspectUser.html', title='At Your Service!',)


@site.route('/transfer/')
@login_required
def transferOut():
    return render_template('transferOut.html', title='At Your Service!',)


@site.route('/admin/')
@login_required
def admin():
    if current_user.email != "danny.oleinik@atyourservice.business":
        flash("you need a higher rank to acess this page.", "error")
        flash(current_user.email)
        return redirect(url_for("site.index"))
    flash("Welcome, Bobby!", "success")
    posted = JobPost.query.filter_by(taken_by=None).all()
    refunded = RemovedPost.query.join(User, User.id == RemovedPost.user_id).add_columns(RemovedPost.price, User.email).all()
    paid = JobPost.query.filter(JobPost.filled != None).join(User, User.id == JobPost.user_id).add_columns(JobPost.price, User.email).all()
    return render_template('admin.html', title='At Your Service!', posted=posted, refunded=refunded, paid=paid)


@site.route('/admin/verify/')
@login_required
def verify():
    if current_user.email != "danny.oleinik@atyourservice.business":
        flash("you need a heigher rank to acess this page. Are you Bobby?", "error")
        return redirect(url_for("site.index"))
    flash("Welcome, Bobby!", "success")
    posts = JobPost.query.filter_by(verified=False).all()
    return render_template('adminVerify.html', title='At Your Service!', posts=posts)


@site.route('/admin/verify/<int:id>/')
def verifyPost(id):
    if current_user.email != "danny.oleinik@atyourservice.business":
        flash("this route is only for admins", "error")
        return redirect(url_for('site.home'))
    post = JobPost.query.filter_by(id=id).first()
    post.verified = True
    db.session.commit()
    flash('post successfully verifed.', 'success')
    return redirect(url_for('site.verify'))


@site.route('/admin/<int:id>/')
def removePost(id):
    if current_user.email == "danny.oleinik@atyourservice.business":
        post = JobPost.query.filter_by(id=id).first()
        user = User.query.filter_by(id=JobPost.user_id).first()
        db.session.delete(post)
        db.session.commit()
        flash('post successfully deleted.', 'warning')
        return redirect(url_for('site.admin'))
    flash("this route is only for admins", "error")
    return redirect(url_for('site.home'))


@site.route('/getPosts/', methods=["GET", "POST"])
def getPosts():
    posts = JobPost.query.all()
    response = dict()
    for post in posts:
        response.update({"post": {
            "title": post.title,
            "description": post.job_description,
            "price": post.price,
            "area": post.area_name,
            "time": post.time,
            "id": post.id,
            "poster_id": post.user_id,
            "verified": post.verified,
            "taken_by": post.taken_by,
        }})
    return jsonify(response)


@site.route('/getPostForModal/taken/<int:post_id>/')
def getModalTaken(post_id):
    post = JobPost.query.filter_by(id=post_id).join(User, User.id == JobPost.user_id).add_columns(
        JobPost.area_name, JobPost.job_description, JobPost.price, JobPost.title, User.email).first()
    return jsonify({
        "title": post.title,
        "location": post.area_name,
        "description": post.job_description,
        "price": post.price,
        "posted_by": post.email,
    })

@site.route('/removeJob/')
def removeJob_():
    return redirect(url_for("site.inspectUser"))

@site.route('/removeJob/<int:post_id>/')
def removeJob(post_id):
    post = JobPost.query.filter_by(id = post_id).first()
    if post.user_id != current_user.id:
        flash("This post was not posted by you.", "danger")
        return redirect(url_for("site.inspectUser"))
    if not post:
        flash("post not found.", "danger")
        return redirect(url_for("site.inspectUser"))
    if post.taken_by != None:
        flash("this post has been taken.", "danger")
        return redirect(url_for("site.inspectUser"))
    JobPost.query.filter_by(id = post_id).delete()
    db.session.add(RemovedPost(user_id = current_user.id, price = post.price))
    db.session.commit()
    flash("post marked as complete! Their payment will be transfered shortly." , "success")

@site.route('/markAsComplete/')
def markComplete_():
    return redirect(url_for("site.inspectUser"))

@site.route('/markAsComplete/<int:post_id>/')
def markComplete(post_id):
    post = JobPost.query.filter_by(id = post_id).first()
    if post.user_id != current_user.id:
        flash("This post was not posted by you.", "danger")
        return redirect(url_for("site.inspectUser"))
    if not post:
        flash("post not found.", "danger")

AtYourService/atyourservice/templates/aboutUs.html
{% extends 'base.html' %}
{% block main %}
{% endblock main %}

AtYourService/atyourservice/templates/addMoney.html
{% extends 'form.html' %}
{% block form %}
<span class = "text-center">Current Money:</span>
<div class ="display-4 text-success text-center">${{ current_user.money }}</div>
    <div class="form-group">
            <label class="font-weight-bold">Amount to add</label>
            {{ form.amount(class = "form-control p-3")}}
            {% if form.amount.errors %}
            <small class = "text-danger">
                {% for error in form.amount.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </small>
            {% endif %}
        </div>
{% endblock form %}

AtYourService/atyourservice/templates/admin.html
{% extends 'base.html' %}
{% block main %}
<a href = "{{ url_for('site.verify') }}"></a>
<h4 class="text-primary">Jobs</h4>
<p>
    List of all jobs. click on a job to inspect it.
</p>
<table class="table table-hover table-sm">
    <thead class="thead-light">
        <tr>
            <th scope="col">Job</th>
            <th scope="col">Pay</th>
            <th scope="col">Remove Post</th>
        </tr>
    </thead>
    <tbody>
            {% for job in posted | reverse %}
            <tr>
                <td>{{ job.job_description }}</td>
                <td class="text-success">{{ "${:,.2f}".format(job.price) }}</td>
                <td><a href = "{{ url_for('site.removePost', id = job.id )}}"><button type="button" class="btn btn-danger">Remove Post</button></a></td>
            </tr>
            {% endfor %}
    </tbody>
</table>
<h4 class="text-primary">These jobs need to be refunded.</h4>
<table class="table table-hover table-sm">
        <thead class="thead-light">
            <tr>
                <th scope="col">Pay</th>
                <th scope="col">email</th>
            </tr>
        </thead>
        <tbody>
                {% for job in refunded | reverse %}
                <tr>
                    <td class="text-success">{{ "${:,.2f}".format(job.price) }}</td>
                    <td>job.email</td>
                </tr>
                {% endfor %}
        </tbody>
    </table>
    <h4 class="text-primary">These jobs need to be paid.</h4>
    <table class="table table-hover table-sm">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Pay</th>
                    <th scope="col">email</th>
                </tr>
            </thead>
            <tbody>
                    {% for job in paid | reverse %}
                    <tr>
                        <td class="text-success">{{ "${:,.2f}".format(job.price) }}</td>
                        <td>job.email</td>
                    </tr>
                    {% endfor %}
            </tbody>
        </table>
{% endblock main %}

AtYourService/atyourservice/templates/adminVerify.html
{% extends 'base.html' %}
{% block main %}
<h4 class="text-primary">Jobs</h4>
<p>
    List of all jobs. click on a job to inspect it.
</p>
<table class="table table-hover table-sm">
    <thead class="thead-light">
        <tr>
            <th scope="col">Job</th>
            <th scope="col">Pay</th>
            <th scope="col">Verify Post</th>
        </tr>
    </thead>
    <tbody>
            {% for job in posts %}
            <tr>
                <td>{{ job.job_description }}</td>
                <td class="text-success">{{ "${:,.2f}".format(job.price) }}</td>
                <td><a href = "{{ url_for('site.verifyPost', id = job.id )}}"><button type="button" class="btn btn-warning">Verify Post</button></a></td>
            </tr>
            {% endfor %}
    </tbody>
</table>
{% endblock main %}

AtYourService/atyourservice/templates/cookiePolicy.html
{% extends 'base.html' %}
{% block header %}
{% endblock header %}
{% block main %}
<div class = "mx-auto mb-5" style = "max-width: 500px;">
<h1 class = "text-center mb-5">Cookie Policy of {{ app_name }}</h1>
<div>
        <p>Cookies consist of portions of code installed in the browser that assist the Owner in providing the Service
                according to the purposes described. Some of the purposes for which Cookies are installed may also
                require the User's consent.
                Where the installation of Cookies is based on consent, such consent can be freely withdrawn at any time
                following the instructions provided in this document.</p>
        <h4 class = "mb-2">Other types of Cookies or third parties that install Cookies</h4>
        <p>
                Some of the services listed below collect statistics in an anonymized and aggregated form and may not
                require the consent of the User or may be managed directly by the Owner - depending on how they are
                described - without the help of third parties.

                If any third party operated services are listed among the tools below, these may be used to track Users’
                browsing habits – in addition to the information specified herein and without the Owner’s knowledge.
                Please refer to the privacy policy of the listed services for detailed information.
        </p>
        <h4 class = "mb-2">Advertising</h4>
        <p>
                This type of service allows User Data to be utilized for advertising communication purposes displayed in
                the form of banners and other advertisements on this Website, possibly based on User interests.
                This does not mean that all Personal Data are used for this purpose. Information and conditions of use
                are shown below.
                Some of the services listed below may use Cookies to identify Users or they may use the behavioral
                retargeting technique, i.e. displaying ads tailored to the User’s interests and behavior, including
                those detected outside this Website. For more information, please check the privacy policies of the
                relevant services.
        </p>
        <h4 class = "mb-2">Analytics</h4>
        <p>
                The services contained in this section enable the Owner to monitor and analyze web traffic and can be
                used to keep track of User behavior.

                Google Analytics (Google Inc.)
                Google Analytics is a web analysis service provided by Google Inc. (“Google”). Google utilizes the Data
                collected to track and examine the use of this Website, to prepare reports on its activities and share
                them with other Google services.
                Google may use the Data collected to contextualize and personalize the ads of its own advertising
                network.
                Personal Data collected: Cookies and Usage Data.

                Place of processing: United States – <a href="https://policies.google.com/privacy?hl=en">Privacy
                        Policy</a> – <a href="https://tools.google.com/dlpage/gaoptout?hl=en">Opt Out</a>. Privacy
                Shield participant.
        </p>
</div>
</div>
{% endblock main %}

AtYourService/atyourservice/templates/form.html
{% extends 'base.html' %}
{% block main %}
<div class="border-primary mx-auto p-4 mb-4 bg-white rounded"
    style="box-shadow: 0px 6px 16px -3px rgba(143,143,143,0.57); max-width: 600px">
    <div class="px-2 py-3">
        <h4 class="text-primary text-center">{{ form_name }}</h4>
        <form method="POST">
            {{ form.hidden_tag() }}
            {%block form %}
            {% endblock form %}
            {{ form.submit(class = "btn btn-primary btn-block p-3 mb-2 text-white") }}
        </form>
    </div>
</div>
{% endblock main %}

AtYourService/atyourservice/templates/home.html
{% extends 'base.html' %}
{% block header %}
<link href="{{ url_for('static', filename='css/grids/home.grid.css') }}" rel="stylesheet" type="text/css">
<script src="{{ url_for('static', filename='js/post_pager.js') }}">
</script>
{% endblock header %}
{% block main %}
<div class="main-grid w-80 p-2 m-auto">
    <div class="border-primary p-4 bg-white rounded" style="box-shadow: 0px 6px 16px -3px rgba(143,143,143,0.57);">
        <div class="p-3 float-right" id="post-count">
            1/12
        </div>
        <div class="p-3 font-weight-bold" style="font-size: 1.2em;">
            Browse Jobs
        </div>
        <div class="job-card" id="job-card">
            <div id="current-user-id" style="display: none;">{{ current_user.id }}</div>
            <div id="poster-id" style="display: none;">-1</div>
            <div id="job-id" style="display: none;">-1</div>
            <div class="font-weight-bold" id="job-card-title">Pending...</div>
            <div id="job-card-address"></div>
            <div id="job-card-time"></div>
            <div id="job-card-price" class="text-success"></div>
            <p id="job-card-body" class="my-2"></p>
        </div>
        <div style="bottom: 1em;">
            <div class="mt-2">
                <div class="text-primary" style="display: inline-block;" onclick=prevPost() id="prev-post">
                    &laquo;
                    Previous
                </div>
                <div class="text-primary float-right display-inline" onclick=nextPost() id="next-post">
                    Next
                    &raquo;
                </div>
            </div>
            <small id = "job-notification" class = "text-center display-inline"></small>
            <button type="button" class="btn btn-primary btn-block p-3 my-2 text-white" data-toggle="modal"
                data-target="#exampleModal" id="take-job-primary">Take Job</button>
        </div>
    </div>
    <div class="border-primary p-4 bg-white rounded" style="box-shadow: 0px 6px 16px -3px rgba(143,143,143,0.57);">
        <div class="p-3 font-weight-bold" style="font-size: 1.2em;">
            Post a Job
        </div>
        <form class="p-2" method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group row">
                <label for="colFormLabelSm" class="col-2 col-form-label col-form-label">Job&nbsp;Title</label>
                <div class="col-sm-10">
                    {{ form.title(class = "form-control")}}
                    {% if form.title.errors %}
                    <small class="text-danger">
                        {% for error in form.title.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </small>
                    {% endif %}
                </div>
            </div>
            <div class="form-group row">
                <label for="colFormLabelSm" class="col-2 col-form-label col-form-label">Location</label>
                <div class="col-sm-10">
                    {{ form.location(class = "form-control")}}
                    {% if form.location.errors %}
                    <small class="text-danger">
                        {% for error in form.location.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </small>
                    {% endif %}
                </div>
            </div>
            <div class="form-group row">
                <label for="colFormLabelSm" class="col-2 col-form-label col-form-label">Price</label>
                <div class="col-sm-10">
                    <div style = "display: flex;">
                        <div style = "display: inline-flex;">$</div>

                    {{ form.price(class = "form-control", style = "display: inline-flex; flex-grow: 100;")}}
                </div>
                    {% if form.price.errors %}
                    <small class="text-danger">
                        {% for error in form.price.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </small>
                    {% endif %}
                </div>
            </div>
            <div class="form-group row">
                <label for="colFormLabelSm" class="col-2 col-form-label col-form-label">Time</label>
                <div class="col-sm-10">
                    {{ form.time(class = "form-control")}}
                    {% if form.time.errors %}
                    <small class="text-danger">
                        {% for error in form.time.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </small>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label class="form-label-sm" for="exampleFormControlTextarea1">Description</label>
                {{ form.description(class = "form-control", rows = "3")}}
                {% if form.description.errors %}
                <small class="text-danger">
                    {% for error in form.description.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </small>
                {% endif %}
            </div>
            {{ form.submit(class = "btn btn-primary btn-block p-3 mb-2 text-white") }}
        </form>
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Are you sure you want this job?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    After you click accept, the other party will be notified that you took the job; you will be given
                    their email
                    to contact them further. Funds will be transfered to your account after the transaction is marked
                    complete on their end.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <a href="{{ url_for('site.takeJob_') }}" id="take_job_button">
                        <button type="button" class="btn btn-primary text-white">Take Job</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endblock main %}

AtYourService/atyourservice/templates/inspectUser.html
{% extends 'base.html' %}
{% block header %}
<script src="{{ url_for('static', filename='js/job_modal.js') }}">
</script>
{% endblock header %}
{% block main %}
<h4 class="text-primary">Jobs Taken</h4>
<p>
    Click on a job to open a list of actions with that job, and the other parties email. Once the other party makes the job as
    complete, money will be transfered into your account. 
</p>
<table class="table table-hover table-sm">
    <thead class="thead-light">
        <tr>
            <th scope="col">Job</th>
            <th scope="col">Your Pay</th>
            <th scope="col">Address</th>
            <th scope="col">Complete</th>
        </tr>
    </thead>
    <tbody>
            {% for job in taken | reverse %}
            <tr data-toggle="modal"
            data-target="#jobModal" onclick = updateJobModal({{ job.id }})>
                <td style = "text-overflow: ellipsis;">{{ job.title }}</td>
                <td class="text-success">{{ "${:,.2f}".format(job.price) }}</td>
                <td>{{ job.area_name }}</td>
                {% if job.filled %}
                <td class="text-success">
                    &#10003;
                </td>
                {% else %}
                <td class="text-danger">
                    &times;
                </td>
                {% endif %}
            </tr>
            {% endfor %}
    </tbody>
</table>
<h4 class="text-primary pt-4">Jobs Posted</h4>
<p>
    Click on a job to mark it as complete, remove it, or contact the other party. You will be fully refunded if you
    remove the job and the job is not taken.

</p>
<table class="table table-hover table-sm">
    <thead class="thead-light">
        <tr>
            <th scope="col">Job</th>
            <th scope="col">You Paid</th>
            <th scope="col">Taken</th>       
            <th scope="col">Complete</th>
        </tr>
    </thead>
    <tbody>
        {% for job in posted | reverse %}
        <tr  data-toggle="modal"
        data-target="#postedModal" onclick = updatePostedModal({{ job.id }})>
            <td>{{ job.title }}</td>
            <td class="text-danger">{{ "${:,.2f}".format(job.price) }}</td>
            {% if job.taken_by is not none  %}
            <td class="text-success">
                &#10003;
            </td>
            {% else %}
            <td class="text-danger">
                &times;
            </td>
            {% endif %}
            {% if job.filled %}
            <td class="text-success">
                &#10003;
            </td>
            {% else %}
            <td class="text-danger">
                &times;
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>


<div class="modal fade" id="jobModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel"
aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="taken-title"></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div>
                <div><b>Location: </b><span id = "taken-location"></span></div>
                <div><b>Price: </b><span id = "taken-price"></span></div>
                <div><b>Job Posted By: </b><span id = "taken-taken"></span></div>
                <div><p id = "taken-description"></p></div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
    </div>
</div>
</div>

<div class="modal fade" id="postedModal" tabindex="-1" role="dialog" aria-labelledby="postedModal"
aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="posted-title"></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div>
                <div><b>Location: </b><span id = "posted-location"></span></div>
                <div><b>Price: </b><span id = "posted-price"></span></div>
                <div><b>Job Taken By: </b><span id = "posted-provided"></span></div>
                <div><p id = "posted-description"></p></div>
            </div>
        </div>
        <div class="modal-footer">
                <a id = "complete-link" href = "{{ url_for('site.markComplete_') }}"><button type="button" class="btn btn-success" id = "complete-button">Mark Complete</button></a>
                <a id = "remove-link" href = "{{ url_for('site.removeJob_') }}"><button type="button" class="btn btn-danger" id = "remove-button">Remove</button></a>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
    </div>
</div>
</div>
{% endblock main %}

AtYourService/atyourservice/templates/login.html
{% extends 'form.html' %}
{% block form %}
<div class="form-group">
        <label class="font-weight-bold">Email address</label>
        {{ form.email(class = "form-control p-3")}}
        {% if form.email.errors %}
        <small class = "text-danger">
            {% for error in form.email.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </small>
        {% endif %}
    </div>
    <div class="form-group">
            <label class="font-weight-bold">Password</label>
            {{ form.password(class = "form-control p-3")}}
            {% if form.password.errors %}
            <small class = "text-danger">
                {% for error in form.password.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </small>
            {% endif %}
        </div>
        <div class = "form-group">
            {{ form.remember() }}
            <label>Remember me?</label>
        </div>
{% endblock form %}

AtYourService/atyourservice/templates/transferOut.html
{% extends 'base.html' %}
{% block main %}
<h1 class = "text-primary text-center">We wish!</h1>
<p class = "text-center">
    Unfortunately, the money on here is only a fiat currency, worth nothing. 
    This site is for proof - of concept purposes only (for now)!
</p>
{% endblock main %}